- hosts: all
  vars_files: 
   variable.yml
  tasks:
  - name: "To install Httpd Software" 
    package:
     name: "httpd"
     state: present
  - name: "Creating Directory"
    file:
     state: directory
     path: "{{ document_Root }}"
  - name: "Uploading Configuration Files"
    template: 
     dest: "/etc/httpd/conf.d/newConfig.conf" 
     src: "/newWork/upload.conf"
  - name: "Deploy a WebPage"
    copy: 
     dest: "{{ document_Root }}/index.html"
     content: "<h1> This is another Website</h1>"
  - name: "Enabling Port 8080 for the webserver"
    firewalld:
     port: 8080/tcp
     state: enabled
     permanent: yes
     immediate: yes
  - name: "Starting the Web Service" 
    service:
     name: "httpd" 
     state: started
